{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"ActionResult": {
		"_Name": "create"
	},
	"OnFailure": "/crud_demo_3/Actions/CreateEntityFailureMessage.action",
	"OnSuccess": "/crud_demo_3/Actions/CreateEntitySuccessMessage.action",
	"Target": {
		"Service": "/crud_demo_3/Services/SampleService.service",
		"EntitySet": "Customers"
	}
}
