{
    "ModalPageFullscreen": false,
    "ModalPage": true,
    "PageToOpen": "/crud_demo_3/Pages/SampleService_PurchaseOrderHeaders/PurchaseOrderHeaders_Edit.page",
    "_Type": "Action.Type.Navigation"
}