{
    "ParentLink": {
        "Property": "PurchaseOrders",
        "Target": {
            "EntitySet": "Suppliers",
            "ReadLink": "{@odata.readLink}"
        }
    },
    "OnFailure": "/crud_demo_3/Actions/CreateEntityFailureMessage.action",
    "OnSuccess": "/crud_demo_3/Actions/CreateEntitySuccessMessage.action",
    "Properties": {
        "CurrencyCode": "#Page:Suppliers_CreatePurchaseOrderHeader/#Control:CurrencyCode/#Value",
        "GrossAmount": "#Page:Suppliers_CreatePurchaseOrderHeader/#Control:GrossAmount/#Value",
        "NetAmount": "#Page:Suppliers_CreatePurchaseOrderHeader/#Control:NetAmount/#Value",
        "PurchaseOrderID": "#Page:Suppliers_CreatePurchaseOrderHeader/#Control:PurchaseOrderID/#Value",
        "SupplierID": "#Page:Suppliers_CreatePurchaseOrderHeader/#Control:SupplierID/#SelectedValue",
        "TaxAmount": "#Page:Suppliers_CreatePurchaseOrderHeader/#Control:TaxAmount/#Value"
    },
    "Target": {
        "EntitySet": "PurchaseOrderHeaders",
        "Service": "/crud_demo_3/Services/SampleService.service"
    },
    "ActionResult": {
        "_Name": "create"
    },
    "_Type": "Action.Type.ODataService.CreateRelatedEntity"
}