{
    "OnFailure": "/crud_demo_3/Actions/RequiredFieldsFailureMessage.action",
    "OnSuccess": "/crud_demo_3/Actions/SampleService/Suppliers/Suppliers_CreateEntity.action",
    "RequiredFields": ["SupplierID"],
    "_Type": "Action.Type.CheckRequiredFields"
}