{
    "Animated": true,
    "CompletionTimeout": 3,
    "Message": "$(L,Action_App_Update_Checking)",
    "OnSuccess": "/crud_demo_3/Actions/Application/AppUpdate.action",
    "_Type": "Action.Type.ProgressBanner"
}