{
    "_Type": "Action.Type.Message",
    "Message": "$(L,Action_Reset_Message)",
    "Title": "$(L,Action_Reset_Title)",
    "OKCaption": "$(L,Action_Yes)",
    "OnOK": "/crud_demo_3/Rules/Application/ResetAppSettingsAndLogout.js",
    "CancelCaption": "$(L,Action_No)"
}