{
    "OnFailure": "/crud_demo_3/Actions/RequiredFieldsFailureMessage.action",
    "OnSuccess": "/crud_demo_3/Actions/SampleService/Stock/Stock_UpdateEntity.action",
    "RequiredFields": ["QuantityLessMin"],
    "_Type": "Action.Type.CheckRequiredFields"
}