{
    "Animated": true,
    "CompletionMessage": "$(L,Action_Log_Upload_Completed)",
    "CompletionTimeout": 2,
    "Message": "$(L,Action_Log_Upload_Started)",
    "OnSuccess": "/crud_demo_3/Actions/Logging/UploadLog.action",
    "_Type": "Action.Type.ProgressBanner"
}